spring.application.name=rabbitmq-producer
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.queueName=classicQueueTest
spring.rabbitmq.exchangeName=classicQueueDirectExchangeTest
spring.rabbitmq.routingKey=classicQueueDirectExchangeRoutingKeyTest
server.port=8081