spring.application.name=rabbitmq-producer
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.queueName=classicQueueTest
spring.rabbitmq.exchangeName=classicQueueDirectExchangeTest
spring.rabbitmq.routingKey=classicQueueDirectExchangeRoutingKeyTest

# Header Exchange Configs
spring.rabbitmq.header.one.queueName=headerExchangeQueueOne
spring.rabbitmq.header.one.exchangeName=headerExchangeOne
spring.rabbitmq.header.one.region=CA
spring.rabbitmq.header.one.priority=high
spring.rabbitmq.header.one.strategy=ALL
spring.rabbitmq.header.one.durable=false
spring.rabbitmq.header.one.exclusive=false
spring.rabbitmq.header.one.autoDelete=false

spring.rabbitmq.header.two.queueName=headerExchangeQueueTwo
spring.rabbitmq.header.two.exchangeName=headerExchangeOne
spring.rabbitmq.header.two.region=EU
spring.rabbitmq.header.two.priority=high
spring.rabbitmq.header.two.strategy=ANY
spring.rabbitmq.header.two.durable=false
spring.rabbitmq.header.two.exclusive=false
spring.rabbitmq.header.two.autoDelete=false

spring.rabbitmq.header.three.queueName=headerExchangeQueueThree
spring.rabbitmq.header.three.exchangeName=headerExchangeOne
spring.rabbitmq.header.three.region=US
spring.rabbitmq.header.three.priority=high
spring.rabbitmq.header.three.strategy=SINGLE
spring.rabbitmq.header.three.durable=false
spring.rabbitmq.header.three.exclusive=false
spring.rabbitmq.header.three.autoDelete=false

spring.rabbitmq.header.four.queueName=headerExchangeQueueFour
spring.rabbitmq.header.four.exchangeName=headerExchangeOne
spring.rabbitmq.header.four.region=CN
spring.rabbitmq.header.four.priority=high
spring.rabbitmq.header.four.strategy=ALL
spring.rabbitmq.header.four.durable=false
spring.rabbitmq.header.four.exclusive=false
spring.rabbitmq.header.four.autoDelete=false

# Topic Exchange Configs
spring.rabbitmq.topic.bangalore.queueName=queue.bengaluru
spring.rabbitmq.topic.bangalore.exchangeName=my.topic.exchange
spring.rabbitmq.topic.bangalore.routingKey=*.BENGALURU
spring.rabbitmq.topic.bangalore.durable=false
spring.rabbitmq.topic.bangalore.exclusive=false
spring.rabbitmq.topic.bangalore.autoDelete=false

spring.rabbitmq.topic.mumbai.queueName=queue.mumbai
spring.rabbitmq.topic.mumbai.exchangeName=my.topic.exchange
spring.rabbitmq.topic.mumbai.routingKey=*.MUMBAI.#
spring.rabbitmq.topic.mumbai.durable=false
spring.rabbitmq.topic.mumbai.exclusive=false
spring.rabbitmq.topic.mumbai.autoDelete=false

spring.rabbitmq.topic.delhi.queueName=queue.delhi
spring.rabbitmq.topic.delhi.exchangeName=my.topic.exchange
spring.rabbitmq.topic.delhi.routingKey=*.DELHI.#
spring.rabbitmq.topic.delhi.durable=false
spring.rabbitmq.topic.delhi.exclusive=false
spring.rabbitmq.topic.delhi.autoDelete=false

spring.rabbitmq.topic.hyderabad.queueName=queue.hyderabad
spring.rabbitmq.topic.hyderabad.exchangeName=my.topic.exchange
spring.rabbitmq.topic.hyderabad.routingKey=*.HYDERABAD
spring.rabbitmq.topic.hyderabad.durable=false
spring.rabbitmq.topic.hyderabad.exclusive=false
spring.rabbitmq.topic.hyderabad.autoDelete=false

# Fanout Exchange Configs
spring.rabbitmq.fanout.fanout_one.queueName=fanoutExchangeQueueOne
spring.rabbitmq.fanout.fanout_one.exchangeName=fanoutExchangeOne
spring.rabbitmq.fanout.fanout_one.durable=false
spring.rabbitmq.fanout.fanout_one.exclusive=false
spring.rabbitmq.fanout.fanout_one.autoDelete=false

spring.rabbitmq.fanout.fanout_two.queueName=fanoutExchangeQueueTwo
spring.rabbitmq.fanout.fanout_two.exchangeName=fanoutExchangeOne
spring.rabbitmq.fanout.fanout_two.durable=false
spring.rabbitmq.fanout.fanout_two.exclusive=false
spring.rabbitmq.fanout.fanout_two.autoDelete=false

spring.rabbitmq.fanout.fanout_three.queueName=fanoutExchangeQueueThree
spring.rabbitmq.fanout.fanout_three.exchangeName=fanoutExchangeOne
spring.rabbitmq.fanout.fanout_three.durable=false
spring.rabbitmq.fanout.fanout_three.exclusive=false
spring.rabbitmq.fanout.fanout_three.autoDelete=false

spring.rabbitmq.fanout.fanout_four.queueName=fanoutExchangeQueueFour
spring.rabbitmq.fanout.fanout_four.exchangeName=fanoutExchangeOne
spring.rabbitmq.fanout.fanout_four.durable=false
spring.rabbitmq.fanout.fanout_four.exclusive=false
spring.rabbitmq.fanout.fanout_four.autoDelete=false
server.port=8081