services:
  haproxy:
    image: haproxy:3.2
    container_name: haproxy_load_balancer
    ports:
      - "5672:5672"
      - "5552:5552"
      - "15672:15672"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - rabbitmq-cluster
    depends_on:
      rabbitmq1:
        condition: service_healthy
      rabbitmq2:
        condition: service_healthy
      rabbitmq3:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    restart: on-failure

  rabbitmq1:
    image: rabbitmq:4-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=my-secret-cookie
      - RABBITMQ_NODENAME=rabbitmq1
    networks:
      - rabbitmq-cluster
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M

  rabbitmq2:
    image: rabbitmq:4-management
    hostname: rabbitmq2
    environment:
      - RABBITMQ_ERLANG_COOKIE=my-secret-cookie
      - RABBITMQ_NODENAME=rabbitmq2
    networks:
      - rabbitmq-cluster
    depends_on:
      rabbitmq1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M

  rabbitmq3:
    image: rabbitmq:4-management
    hostname: rabbitmq3
    environment:
      - RABBITMQ_ERLANG_COOKIE=my-secret-cookie
      - RABBITMQ_NODENAME=rabbitmq3
    networks:
      - rabbitmq-cluster
    depends_on:
      rabbitmq1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M

networks:
  rabbitmq-cluster: